name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: arduino/arduino-cli:drone-1.1.0
      volumes:
        # cache go dependencies across pipeline's steps
        - $PWD/go:/go

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: check
        # Check if the Go code is properly formatted and run the linter and
        # ensure protobufs compile without errors
        run: task check

      - name: build
        # Build the CLI
        run: task build

      - name: test
        # Run unit tests
        run: task test-unit

      - name: test-legacy
        # Run unit tests on the legacy package
        run: task test-legacy

      - name: test-integrations
        # Run integration tests
        run: |
          pip install -r test/requirements.txt
          task test-integration

      - name: coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        # Send results to codecov
        run: |
          codecov -cF unit -f coverage_unit.txt -t $CODECOV_TOKEN
          codecov -cF integ -f coverage_integ.txt -t $CODECOV_TOKEN
